sudo: false
language: c
os: 
    - linux
    - osx

compiler:
  - gcc

before_install: ./brew/brew_install.sh
   
addons:
  apt:
    packages:
      - libnetcdf-dev
      - libhdf5-serial-dev

script: 
        - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DLIBMINC_MINC1_SUPPORT:BOOL=OFF -DBUILD_TESTING:BOOL=ON
        - make
        - make test
        - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DLIBMINC_MINC1_SUPPORT:BOOL=ON -DBUILD_TESTING:BOOL=ON
        - make
        - make test
